//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarketPlaces.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SpamReport
    {
        public int UserID { get; set; }
        public int NoteID { get; set; }

        [Required]
        public string Remark { get; set; }

        public string Title { get; set; }
        public string Category { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public int ID { get; set; }
        public bool IsActive { get; set; }

        public virtual NoteDetail NoteDetail { get; set; }
        public virtual User User { get; set; }
    }
}